### ISSUE TITLE
Update TLV Library to handle large messages

### ISSUE THREAD

**Issue by maevyn11** [GridPlus/phonon-client#137]
The current TLV encoding/decoding library only handles message with lengths fitting inside a single byte (<=256 bytes.) This is technically an incorrect implementation of the BerTLV standard which was undertaken for expediency. 

Now, with the advent of extended length messaging on the cards expanding the maximum message size from 256 to over 1k bytes we need to update this library to handle messages of any length. There is a BerTLV standard for this which provides a prefix byte before TLV messages to indicate whether the length will be given in one or two bytes. This is currently being implemented by Mike on the cards. 

It should be investigated whether this is the most appropriate protocol for encoding data between the card and client and if it is, it needs to be implemented on the client to match the changes taking place on the card.

**Comment by MSalopek** [comment]
Looking into this.

**Comment by SecureElement** [comment]
this is a deviation due to smart card limitations on memory

**Comment by maevyn11** [comment]
Update on this, due to some difficulty merging this in directly I cherrypicked these changes onto the dv-beta-merge branch, which we intend to merge into the 'beta' branch once the phonon-card's corresponding branch is passing regression tests. 

All this code in the client side TLV handling is performing well and hasn't given us a problem so far. Still a little ways to go on testing out the card side.
