### ISSUE TITLE
Automatically set up mockCard in frontend when no connected card is connected

### ISSUE THREAD

**Issue by maevyn11** [GridPlus/phonon-client#175]
It would be a nice feature to have the frontend GUI make a call to the client to generate a mock card when it sees that there is currently no card connected. This would be nice for users who don't currently have a card to play around with the app. 

The fact that it's a mock should be clearly indicated alongside the name/cardID to avoid confusion.

**Comment by npmaile** [comment]
this should be an issue on the frontend repo. The client shouldn't be doing this automatically as developers and other frontends may not want this behavior

**Comment by npmaile** [comment]
button was added to frontend to generate a mock if there is no card in https://github.com/GridPlus/phonon-app/commit/496b39535a204b548aff4846a95fb02056e15c1b which has since been put in this repo.
