### ISSUE TITLE
Refresh, back, and forward Browser buttons lead to broken pages

### ISSUE THREAD

**Issue by maevyn11** [GridPlus/phonon-client#216]
Issue: Reloading the page breaks everything
Steps to recreate: Reload the page
Means to resolve: Completely quitting  and restarting the app and unlocking works.
OS:  OSX 12.3.1 (21E258)
Browser: Brave 1.42.86

From a reported testnet bug. The refresh, back, and forward browser buttons should behave sensibly inside the app or be removed somehow. As is they usually lead to a broken page and a need to restart the app if used.

**Comment by npmaile** [comment]
https://github.com/GridPlus/phonon-client/pull/219
