### ISSUE TITLE
Unlocking a card sometimes kicks user back to lock screen

### ISSUE THREAD

**Issue by maevyn11** [GridPlus/phonon-client#226]
This is an intermittent issue that occurs somewhat unpredictably. After a user clicks unlock on the UI the home screen will flash but then they'll be dropped back to the card display screen and need to unlock their card again to proceed. Some users have reported getting into a loop state where this occurs several times. 

I've been able to replicate it myself a couple times, and it seems it may be related to an error result coming back from the GetFriendlyName call when it tries to contact the card to retrieve a FriendlyName for the first time, but I haven't definitely identified it. 

Probably just some improvements to error handling required to eliminate this issue. May cut across both the client and UI.

**Comment by npmaile** [comment]
fixed in https://github.com/GridPlus/phonon-client/pull/228
