### ISSUE TITLE
Client crashes when listing a mumbai phonon created before 'chainID fix'

### ISSUE THREAD

**Issue by ahinchliff** [GridPlus/phonon-client#305]
### Problem

If a mumbai phonon was created before the merge of #300 it's chainID wasnt stored correctly. #300 fixed this but isnt backwards compatible.  Listing one of these faulty chainID phonons causes the client to crash with `panic: runtime error: index out of range [3] with length 1`. 

### Expected Behaviour

Not sure if it is worth adding a fix for this

### Steps to reproduce

1. Revert the merge of #300
2. Start client, unlock & `create`
4. `setDescriptor 10 2 80001 1`
5. Quit client, checkout master, start client, unlock && `list`.

**Comment by npmaile** [comment]
let's skip it.

**Comment by npmaile** [comment]
I take it back.

**Comment by npmaile** [comment]
fixed in pr above
